name: "Test"
on:
  push:
    branch: [main]

job:
  test_merge_id:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    run: |
      mkdir temp
      cd temp
      touch test.txt
      

        


      

